In [ ]:
import numpy as np

a = np.array([1,2,3]) #1d
b = np.array([[1,2],[3,4]]) #2d
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3d
d = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])

print("1D array:")
print(a)
print("2D array:")
print(b)
print("3D array:")
print(c)
print("4D array:")
print(d)

print("shape of 1d array" ,a.shape)
print("shape of 2d array" ,b.shape)
print("shape of 3d array" ,c.shape)
print("shape of 4d array" ,d.shape)
print("dimesnsion of array 1",a.ndim)
print("dimesnsion of array 2",b.ndim)
print("dimesnsion of array 3",c.ndim)
print("dimesnsion of array 4",d.ndim)


1D array:
[1 2 3]
2D array:
[[1 2]
 [3 4]]
3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4D array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
shape of 1d array (3,)
shape of 2d array (2, 2)
shape of 3d array (2, 2, 2)
shape of 4d array (2, 2, 2, 2)
dimesnsion of array 1 1
dimesnsion of array 2 2
dimesnsion of array 3 3
dimesnsion of array 4 4


In [ ]:
import numpy as np

sales_data = np.array([
    [100,200,150,300],
    [100,500,410,324],
    [230,540,890,450],
    [789,360,452,120]
])

sales_data[2] #for acessing a row

array([230, 540, 890, 450])

In [ ]:
sales_data[:,1] #: is for row means all rows and 1 is for column here we are taking 1 column value

array([200, 500, 540, 360])

In [ ]:
sales_data[sales_data > 300] #all values in my array > 300

array([500, 410, 324, 540, 890, 450, 789, 360, 452])

In [ ]:
sales_data[[1,2],2] #[1,2] goes for rows and the other 2 is column
#here we r acessing 2 column and 1 row and 2 row

array([410, 890])

In [ ]:
#broadcasting
a = np.array([1,2,2])
b = 5
print(a+b)
print(a[1] + b) #adding to index 1 element

[6 7 7]
7


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c)


[5 7 9]


In [ ]:
row1 = sales_data[0] #extracting teh first row
print(row1)
discount = row1 * 0.2 #and mutlyping it with 0.2
print(discount) #in the o/p  . represents float values

[100 200 150 300]
[20. 40. 30. 60.]


In [ ]:
cost = np.array([10,20,30,40])
profit = (sales_data - cost)
print(profit)

[[ 90 180 120 260]
 [ 90 480 380 284]
 [220 520 860 410]
 [779 340 422  80]]


In [ ]:
from numpy import *
a =  ones([2,5],int) #here 2 rows of ones and 5 columns of ones and type is int
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
array = np.array([10,4,6,8.5,9])

print(sqrt(array))
print(max(array))
print(sort(array))
print(mean(array))
print(sin(array))


[3.16227766 2.         2.44948974 2.91547595 3.        ]
10.0
[ 4.   6.   8.5  9.  10. ]
7.5
[-0.54402111 -0.7568025  -0.2794155   0.79848711  0.41211849]


In [ ]:
x = arange(0,21,2) #2o is exclusive
print(x) #arange(start, stop , step )

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
y = logspace(1,6,10) #returns log values
print(y)

[1.00000000e+01 3.59381366e+01 1.29154967e+02 4.64158883e+02
 1.66810054e+03 5.99484250e+03 2.15443469e+04 7.74263683e+04
 2.78255940e+05 1.00000000e+06]


In [ ]:
#linspace() genrates random numbers
import numpy as np
a = linspace(1,10,8) #from 1 to 10 and gets only 10 numbers
print(a)
b = linspace(1,10) #from 1 to 10
print(b)
c = b[:8] #slicing the first 8 elements , [2:8] gives elements from 2 to 8
print(c)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]
[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1.         1.18367347 1.36734694 1.55102041 1.73469388 1.91836735
 2.10204082 2.28571429]


In [ ]:
#reshaping the array
a = np.array([1,2,3,4])
a = a.reshape(2,2)
print(a)

b = np.array([1,2,3,4,5,6,7,8])
b = b.reshape(2,2,2)
print(b)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
a = np.arange(-2,6,1)
b = a.reshape(2,4)
print("array of a :\n" ,a)
print("\narray b :\n" ,b)
print("\nsum of array b      = ",sum(b))
print("length of array b   = ",size(b))
print("avearage of b       = ",average(b))
a[a < 0]

array of a :
 [-2 -1  0  1  2  3  4  5]

array b :
 [[-2 -1  0  1]
 [ 2  3  4  5]]

sum of array b      =  12
length of array b   =  8
avearage of b       =  1.5


array([-2, -1])

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[4,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [4, 6],
       [7, 8]])